const Database = {
    ProductItems: [
        {
            id: 1,
            //discount: 10,
            cover: "./products/cf.jpg",
            name: "Cà phê đen đá",
            price: "10.000",
        },
        {
            id: 2,
            //discount: 10,
            cover: "./products/americano.jpg",
            name: "Americano đá",
            price: "25.000",
        },
        {
            id: 3,
            //discount: 5,
            cover: "./products/cfs.jpg",
            name: "Cà phê sữa đá",
            price: "15.000",
        },
        {
            id: 4,
            //discount: 15,
            cover: "./products/bx.jpg",
            name: "Bạc xỉu đá",
            price: "15.000",
        },
        {
            id: 6,
            //discount: 20,
            cover: "./products/latte.jpg",
            name: "Latte đá",
            price: "30000",
        },
        {
            id: 5,
            //discount: 50,
            cover: "./products/tt.jpg",
            name: "Trà tắc",
            price: "12.000",
        },

    ],
    ProductCakes: [
        {
            id: 12,
            //discount: 10,
            cover: "./products/bonglan_trungmuoi3.jpg",
            name: "Bánh bông lan trứng muối",
            price: "50.000",
        },
        {
            id: 13,
            //discount: 10,
            cover: "./products/donut2.jpg",
            name: "Bánh donut",
            price: "25.000",
        },
        {
            id: 14,
            //discount: 5,
            cover: "./products/suHan.jpg",
            name: "Bánh su Hàn Quốc",
            price: "15.000",
        },
        {
            id: 15,
            //discount: 15,
            cover: "./products/crepe.jpg",
            name: "Bánh crepe",
            price: "15.000",
        },
        {
            id: 16,
            //discount: 20,
            cover: "./products/cuon_suatuoi.jpg",
            name: "Bánh bông lan cuộn sữa tươi",
            price: "30.000",
        },
        {
            id: 17,
            //discount: 50,
            cover: "./products/sukem.jpg",
            name: "Bánh su kem",
            price: "12.000",
        },
        {
            id: 18,
            //discount: 50,
            cover: "./products/mufin_1.jpg",
            name: "Bánh muffin",
            price: "12.000",
        },
    ],
    ProductMt: [
        {
            id: 21,
            //discount: 10,
            cover: "./products/trasua_1.jpg",
            name: "Trà sữa trân châu",
            price: "25.000",
        },
        {
            id: 22,
            //discount: 10,
            cover: "./products/tsm.jpg",
            name: "Trà sữa matcha",
            price: "25.000",
        },
        {
            id: 23,
            //discount: 5,
            cover: "./products/dd.jpg",
            name: "Sữa tươi trân châu đường đen",
            price: "25.000",
        },
        {
            id: 24,
            //discount: 15,
            cover: "./products/tsd.jpg",
            name: "Trà sữa hương dâu",
            price: "25.000",
        },
        {
            id: 25,
            //discount: 20,
            cover: "./products/htc.jpg",
            name: "Hồng trà kem cheese",
            price: "30.000",
        },
        {
            id: 26,
            //discount: 50,
            cover: "./products/olong.jpg",
            name: "Trà sữa olong",
            price: "25.000",
        },
    ],
}
export default Database